### ISSUE TITLE
suggested revisions for python intro from office hours

### ISSUE THREAD

**Issue by matsen** [fredhutchio/intro-bioinformatics#14]
- [x] a little more about namespaces and import (a student suggested that namespaces are like "folders" of names)
- [x] shebang for python scripts
- [x] an argument to a function substitutes the specified value 
- [x] pip is like the App Store or Android Marketplace

**Comment by metasoarous** [comment]
I'm thinking it might be better to emphasize modules and attributes over namespaces per se. That's basically all namespaces are in python. In that sense I think namespaces are like the paths to some object through some graph (should be tree, but I've seen weird things) of modules/objects.

I'll be covering shebang once we start writing programs. Seems to make more sense that way.

Absolutely agree that function arguments being substituted with passed in values could be made more clear. I'll add that somewhere.

Hahaha. Yes. That makes it quite clear doesn't it :-) "It's like apt-get for python! ... <crickets>"

**Comment by atombaby** [comment]
> I'll be covering shebang once we start writing programs. Seems to make more sense that way.

Sorry if this is obvious, but for hash-bang we need to use `/usr/bin/env <interpreter>` to ensure that the currently module loaded {python,Rscript,perl} is used.

> Absolutely agree that function arguments being substituted with passed in 
> values could be made more clear. I'll add that somewhere.

It may be a little too obscure for this class, but I've been bit by pass-by-reference/pass-by-value issues with functions.  IIRC, passing in dictionaries into functions is particularly hairy.

**Comment by matsen** [comment]
> I'm thinking it might be better to emphasize modules and attributes over namespaces per se. That's basically all namespaces are in python. In that sense I think namespaces are like the paths to some object through some graph (should be tree, but I've seen weird things) of modules/objects.

OK, sure. The point either way should be to make it clear that modules help us prevent collisions between functions that have the same name.

**Comment by matsen** [comment]
Oh, and :+1: for something about _names_ in python (I think this might be easier to explain than passing semantics). I have found http://python.net/~goodger/projects/pycon/2007/idiomatic/handout.html#python-has-names to be an especially good explanation.

**Comment by metasoarous** [comment]
@atombaby Totally onboard with `/usr/bin/env python` (etc). That's what I typically do.

@matsen: Yes; that's a good point regarding naming collisions. I can highlight that as a motivating factor and goal.

As for passing semantics etc, I think that most of the weirdness in all this ends up coming down to mutability; that's the real bugaboo. I've been meaning to highlight this somewhere, but not sure where yet. Might add a slide to the OOP class to clarify this (since OOP is typically very stateful).

I think I knew at one point that python used names instead of more traditional variables, but I'd totally forgotten. I'll think about how/where it might make sense to integrate that.

**Comment by matsen** [comment]
LOL. You want to induct these poor souls into the church of immutability. 

Sorry, I know you will disagree, but I'm going to be the pointy-headed boss here and say that it's beyond scope.

**Comment by matsen** [comment]
Re the link above, this one actually has the missing example: http://doc.sagemath.org/html/en/thematic_tutorials/tutorial-objects-and-classes.html#other-languages-have-variables

**Comment by metasoarous** [comment]
:-) I don't want to induct them into the church, just to let them know that mutability/state is a double edged sword, and that they have to be careful about it.

Variables vs names is entirely irrelevant if things are immutable. That's why I think state is the real issue here.

**Comment by matsen** [comment]
Still don't see what this contributes to a Python class though. There are very few immutable constructs in Python.

**Comment by metasoarous** [comment]
Numerics, tuples and strings are immutable. Lists, dicts and objects aren't. 

Aside from that though, you still have the choice of returning a new data structure in your functions, rather than building on one passed in as an arg. And it still pays to be aware of mutability issues as relate to things like [default parameter values](http://python.net/~goodger/projects/pycon/2007/idiomatic/handout.html#default-parameter-values).

All I'm talking about is one slide; nothing dogmatic (not "mutability is evil" just "be careful with mutability"). If you still don't approve though, I'm not overly attached.

**Comment by metasoarous** [comment]
FWIW, I didn't include this, but what do you think? Single non-dogmatic slide?

**Comment by matsen** [comment]
I don't much see the point, but if it makes you happy then OK.
