### ISSUE TITLE
Get everyone on zsh?

### ISSUE THREAD

**Issue by metasoarous** [fredhutchio/intro-bioinformatics#31]
They use it in the book, and the improved autocomplete really is quite helpful... In theory it shouldn't be too difficult to have everyone make the switch, but for some reason `chsh` fails for us...

**Comment by atombaby** [comment]
`chsh` will fail as the integration between Active Directory and our LDAP environment isn't set up to do that.  Users would have to request a shell change via scicomp@fhcrc.org

I am also rather against moving everyone _en masse_ to `zsh`.  `zsh` has many features and does a really good job in the interactive environment.  That said, I have not seen `zsh` used for scripting tasks and I don't know that it provides features in a scripting environment that justify widespread adoption (if you're looking to _really_ get work done, you're typically using a higher-level lanugage like python, perl).  

`bash` remains the default shell in GNU/Linux environment and a _lingua_ _franca_ for exchange with others.  Today, just due to that default, most of the support the students will find from peers and lab-mates will be with `bash`.  As these folks _will_ therefore need to read (and likely write) bash scripts, by switching to `zsh` we're essentially asking our users to learn both `zsh` and `bash`.

That's where I sit- that said, we do support `zsh`, but it's definitely not a primary skill for most of us on the support side.

**Comment by matsen** [comment]
I've used zsh for years and have never seen a zsh-specific script. (Are there some in the book?) I think the intent here is just to get people to have fancier tabbing completion. 

That said, I'm neutral about what's best. @atombaby makes good points about default installs, and I'd imagine not all postdocs will move on to an institution that supports zsh.

**Comment by metasoarous** [comment]
As @matsen suggests, the point isn't scripting. Shebangs make that a non-issue anyway. It's really about just making the shell a friendlier place.

However, if it would be required that scicomp make the switch, I'm disinclined from going this direction. I might just suggest to people that if they're interested they can make the request themselves.

Thanks
